/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgenciaRouteImport } from './routes/agencia'
import { Route as IndexRouteImport } from './routes/index'

const AgenciaRoute = AgenciaRouteImport.update({
  id: '/agencia',
  path: '/agencia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencia': typeof AgenciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencia': typeof AgenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agencia': typeof AgenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agencia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agencia'
  id: '__root__' | '/' | '/agencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenciaRoute: typeof AgenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agencia': {
      id: '/agencia'
      path: '/agencia'
      fullPath: '/agencia'
      preLoaderRoute: typeof AgenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenciaRoute: AgenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
